---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Given any three random integers — X, Y and Z — what are the chances that their product is divisible by 100?

```{r}

library(tidyverse)

theme_set(theme_minimal())


div_by_100 <- function(n, times) {
  
  a <- sample(1:n, times, replace = TRUE)
  b <- sample(1:n, times, replace = TRUE)
  c <- sample(1:n, times, replace = TRUE)
  
  dat <- tibble(a, b, c)
  
  dat$product <- dat$a * dat$b * dat$c
  
  mean(dat$product %% 100 == 0)
}

set.seed(2019)

n <- 1000

results <- tibble(
  x = 1:n,
  pct_div_by_100 = map_dbl(1:n, ~div_by_100(.x, 10000))
)

ggplot(results, aes(x, pct_div_by_100)) +
    geom_line() +
    geom_hline(yintercept = 0.1243, linetype = 3)
    scale_y_continuous(labels = scales::percent_format()) +
    labs(
      x = "range",
      y = "percent divisible by 100",
      title = "Percent of random products divisible by 100 for 1 to max",
      subtitle = "represents 10,000 draws with at each possible max value"
    )

```

